variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_IMAGE_GCC: embeddedlinux/gcc:11-22.04
  DOCKER_IMAGE_CLANG: embeddedlinux/clang:14-22.04
  DOCKER_IMAGE_ARM_LINUX_GCC: embeddedlinux/arm-none-linux-gnueabihf-gcc:11-22.04
  DOCKER_IMAGE_ARM_LINUX_CLANG: embeddedlinux/arm-none-linux-gnueabihf-clang:14-22.04
  DOCKER_IMAGE_ARM_TESTS: embeddedlinux/arm-tests:11-22.04
  DOCKER_IMAGE_VALGRIND: embeddedlinux/valgrind:22.04
  DOCKER_IMAGE_DOXYGEN: embeddedlinux/doxygen:22.04

.Submodule_Checkout:
  variables:
    GIT_DEPTH: 0
  before_script:
    - |
      if [ "${CI_PIPELINE_SOURCE}" == "pipeline" ]; then
          if [ "${TRIGGER_SOURCE_PROJECT}" == "embeddedlinux/libs/hal-interfaces" ]; then
              SUBMODULE_PATH="lib/interfaces"
          elif [ "${TRIGGER_SOURCE_PROJECT}" == "embeddedlinux/libs/hal-drivers" ]; then
              SUBMODULE_PATH="lib/drivers"
          elif [ "${TRIGGER_SOURCE_PROJECT}" == "embeddedlinux/libs/hal-linux" ]; then
              SUBMODULE_PATH="lib/platform/linux"
          fi

          cd ${SUBMODULE_PATH}
          echo "Checking out: ${SUBMODULE_PATH} ${TRIGGER_SOURCE_COMMIT}"
          git checkout ${TRIGGER_SOURCE_COMMIT}
          cd -
      fi

stages:
  - build-GCC
  - build-Clang
  - test
  - valgrind
  - coverage
  - quality
  - deploy

include:
  - "/.gitlab/ci/build-linux.yml"
  - "/.gitlab/ci/coverage-linux.yml"
  - "/.gitlab/ci/deploy.yml"
  # - "/.gitlab/ci/quality.yml"
  # - "/.gitlab/ci/test-linux.yml"
  - "/.gitlab/ci/valgrind-linux.yml"
